### ISSUE TITLE
Create designs for the map

### ISSUE THREAD

**Issue by Steven-Jia** [uwblueprint/water-festival#3]
**TODO**

- [x] @steven-jia Contact WWCGF to get brand colours and assets
- [x] Set up call to review designs
- [ ] Finalize mid-fidelity designs
